Document: auks
Title: Debian auks Manual
Author: <insert document author here>
Abstract: This manual describes what auks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/auks/auks.sgml.gz

Format: postscript
Files: /usr/share/doc/auks/auks.ps.gz

Format: text
Files: /usr/share/doc/auks/auks.text.gz

Format: HTML
Index: /usr/share/doc/auks/html/index.html
Files: /usr/share/doc/auks/html/*.html
